Rails:
  Enabled: true

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - 'bin/*'
    - '*/vendor//'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'lib/tasks/populate.rake'
    - 'config/routes.rb'
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: true
Rails/EnvironmentVariableAccess:
  Enabled: false
Metrics/AbcSize:
  AllowedMethods:
    - load_permissions
Metrics/CyclomaticComplexity:
  AllowedMethods:
    - load_permissions
Metrics/MethodLength:
  AllowedMethods:
    - load_permissions
