version: "3.1"

services:

  db:
    image: postgres
    container_name: ubuteco_db
    ports:
      - 5432:5432
    tty: true
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  adminer:
    image: adminer
    container_name: ubuteco_adminer
    ports:
      - 8080:8080

  mailcatcher:
    image: schickling/mailcatcher
    container_name: ubuteco_mailcatcher
    tty: true
    ports:
      - 1080:1080
      - 1025:1025

#  api:
#    image: cookiecode/base-ruby-on-rails
#    container_name: ubuteco_api
#    ports:
#      - 3000:3000
#    volumes:
#      - .:/var/www
#      - .bundle:/usr/local/bundle
#      - .coverage:/var/www/.coverage
#    stdin_open: true
#    tty: true
#    links:
#      - db

