json.extract! order,
              :id,
              :total,
              :total_with_discounts,
              :discount,
              :table,
              :table_id,
              :organization,
              :organization_id,
              :status,
              :user_id,
              :user,
              :created_at,
              :updated_at
