GET http://{{host}}:{{port}}/api/users
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

PUT http://{{host}}:{{port}}/api/users/1
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Admin"
}

###
