POST http://{{host}}:{{port}}/auth/password
Accept: application/json
Content-Type: application/json

{
  "email": "admin@cookiecode.com.br"
}

###

POST http://{{host}}:{{port}}/auth/code
Accept: application/json
Content-Type: application/json

{
  "code": "827760"
}

> {%
 if(response.status == 200)
client.global.set("reset_token", response.body.token)
 %}


###

PUT http://{{host}}:{{port}}/auth/reset_passwords
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{reset_token}}

{
  "password": "strogonoff123"
}


