POST http://{{host}}:{{port}}/auth/sign_up
Accept: application/json
Content-Type: application/json

{
  "user": {
    "email": "asdasdads@email.com",
    "password": "123123123",
    "name": "teste"
  },
  "organization_attributes": {
    "name": "cookiedcode",
    "phone": "asdasdasd",
    "cnpj": "40.219.165/0001-73"
  }
}
