json.extract! item,
              :id,
              :order_id,
              :quantity,
              :item_type,
              :item_id,
              :item,
              :status,
              :created_at,
              :updated_at
