POST http://{{host}}:{{port}}/api/users
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "email": "cozinha12@asd.com",
  "name": "cozinha1",
  "password": "123123123",
  "role_id": 1,
  "organization_id": 1
}

###

PUT http://{{host}}:{{port}}/api/users/1
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "name": "cozinha1"
}

###

DELETE http://{{host}}:{{port}}/api/users/1
Content-Type: application/json
Accept: application/json
Authorization: {{token}}
