# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://{{host}}:{{port}}/api/wine_styles
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Strong Golsden Ale"
}

> {% client.global.set("style_id", response.body.id) %}

###

GET http://{{host}}:{{port}}/api/wine_styles
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

GET http://{{host}}:{{port}}/api/wine_styles/{{style_id}}
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

PUT http://{{host}}:{{port}}/api/wine_styles/{{style_id}}
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Strong Golden Ale"
}

###

DELETE http://{{host}}:{{port}}/api/wine_styles/{{style_id}}
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###
