

POST http://{{host}}:{{port}}/api/dishes
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "name": "sanduba",
  "price": 15,
  "dish_ingredients_attributes": [
    {
      "food_id": 1,
      "quantity": 10
    }
  ]
}

> {% client.global.set("item_id", response.body.id) %}

###

GET http://{{host}}:{{port}}/api/dishes
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

###

GET http://{{host}}:{{port}}/api/dishes/2
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###

PUT http://{{host}}:{{port}}/api/dishes/{{id}}
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "name": "sanduba",
  "price": 15,
  "dish_ingredients_attributes": [
    {
      "food_id": 1,
      "quantity": 10
    }
  ]
}


###

DELETE http://{{host}}:{{port}}/restaurant_menus/{{menu_item_id}}
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###
