GET http://{{host}}:{{port}}/api/dishes/105/ingredients
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

###

POST http://{{host}}:{{port}}/api/dishes/78/ingredients
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "food_id": 42,
  "quantity": 3
}
